//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVRAMTuner.Client.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NVRAMTuner.Client.Services.Resources.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sh.
        /// </summary>
        public static string BourneShellCommand {
            get {
                return ResourceManager.GetString("BourneShellCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chmod +x.
        /// </summary>
        public static string ChmodExecuteCommand {
            get {
                return ResourceManager.GetString("ChmodExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;nvramver&quot;: {&quot;default&quot;: &quot;RTCONFIG_NVRAM_VER&quot;, &quot;description&quot;: &quot;&quot;}, &quot;restore_defaults&quot;: {&quot;default&quot;: &quot;0&quot;, &quot;description&quot;: &quot;Set to 0 to not restore defaults on boot&quot;}, &quot;sw_mode&quot;: {&quot;default&quot;: &quot;1&quot;, &quot;description&quot;: &quot;big switch for different mode&quot;}, &quot;ASUS_EULA&quot;: {&quot;default&quot;: &quot;0&quot;, &quot;description&quot;: &quot;&quot;}, &quot;preferred_lang&quot;: {&quot;default&quot;: &quot;EN&quot;, &quot;description&quot;: &quot;&quot;}, &quot;wan_ifnames&quot;: {&quot;default&quot;: &quot;0&quot;, &quot;description&quot;: &quot;&quot;}, &quot;lan_ifnames&quot;: {&quot;default&quot;: &quot;vlan0 eth1 eth2 eth3&quot;, &quot;description&quot;: &quot;&quot;}, &quot;lan1_ifnames&quot;: {&quot;default&quot;: &quot; }&quot;, &quot;descrip [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirmwareVariableDefaults {
            get {
                return ResourceManager.GetString("FirmwareVariableDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostname.
        /// </summary>
        public static string HostNameCommand {
            get {
                return ResourceManager.GetString("HostNameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/sh
        ///
        ///# THIS SCRIPT WAS TAKEN FROM https://www.snbforums.com/threads/asus-rt-ac68u-386-2_6-low-on-free-nvram.73158/post-695283
        ///# It is licensed according to the wider SNBForums Ts&amp;Cs: https://www.snbforums.com/help/terms/
        ///
        ///echo &quot;Removing unused cert/key from nvram...&quot;
        ///
        ///for i in 1 2 3 4 5
        ///do
        ///    nvram unset vpn_crt_client$i\_ca
        ///    nvram unset vpn_crt_client$i\_extra
        ///    nvram unset vpn_crt_client$i\_crt
        ///    nvram unset vpn_crt_client$i\_key
        ///    nvram unset vpn_crt_client$i\_crl
        ///    nvram  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MerlinCertClearScript {
            get {
                return ResourceManager.GetString("MerlinCertClearScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvram commit.
        /// </summary>
        public static string NvramCommitCommand {
            get {
                return ResourceManager.GetString("NvramCommitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvram set.
        /// </summary>
        public static string NvramSetCommand {
            get {
                return ResourceManager.GetString("NvramSetCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvram show.
        /// </summary>
        public static string NvramShowCommand {
            get {
                return ResourceManager.GetString("NvramShowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!/bin/sh
        ///
        ///# This file was auto-generated by NVRAMTuner on {0}
        ///
        ///
        ///{1}.
        /// </summary>
        public static string NvramTunerShTemplate {
            get {
                return ResourceManager.GetString("NvramTunerShTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uname -o.
        /// </summary>
        public static string UnameOsCommand {
            get {
                return ResourceManager.GetString("UnameOsCommand", resourceCulture);
            }
        }
    }
}
